### ISSUE TITLE
OutOfMemoryException during decompress

### ISSUE THREAD

**Issue by IlyaSemenov** [chromelyapps/Chromely#151]
Running a Chromely app always ends up like this on a 2GB Windows 7 machine:

```
2020-01-21 20:06:56.315 [INFO] CefLoader: Installing CEF runtime from http://opensource.spotify.com/cefbuilds
2020-01-21 20:06:56.648 [INFO] CefLoader: Load CEF for Windows X86, version 3865
2020-01-21 20:06:56.669 [INFO] CefLoader: Load index page http://opensource.spotify.com/cefbuilds/index.html#windows32_b
uilds
2020-01-21 20:06:59.118 [INFO] CefLoader: Found download URL http://opensource.spotify.com/cefbuilds/cef_binary_77.1.18%
2Bg8e8d602%2Bchromium-77.0.3865.120_windows32_minimal.tar.bz2
2020-01-21 20:06:59.277 [INFO] CefLoader: Parallel download cef_binary_77.1.18%2Bg8e8d602%2Bchromium-77.0.3865.120_windo
ws32_minimal.tar.bz2, 123MB
2020-01-21 20:06:59.418 [INFO] CefLoader: Load C:\Users\kengu\AppData\Local\Temp\tmp913D.tmp (97088808..129451745)
2020-01-21 20:06:59.423 [INFO] CefLoader: Load C:\Users\kengu\AppData\Local\Temp\tmp913E.tmp (64725872..97088807)
2020-01-21 20:06:59.451 [INFO] CefLoader: Load C:\Users\kengu\AppData\Local\Temp\tmp913F.tmp (32362936..64725871)
2020-01-21 20:06:59.454 [INFO] CefLoader: Load C:\Users\kengu\AppData\Local\Temp\tmp915F.tmp (0..32362935)
2020-01-21 20:07:38.854 [INFO] CefLoader: Download took 42195ms
2020-01-21 20:07:38.859 [INFO] CefLoader: Decompressing BZ2 archive
2020-01-21 20:08:01.474 [INFO] CefLoader: Decompress progress = 10%
2020-01-21 20:08:20.890 [INFO] CefLoader: Decompress progress = 20%
2020-01-21 20:08:40.840 [INFO] CefLoader: Decompress progress = 30%
2020-01-21 20:09:02.151 [INFO] CefLoader: Decompress progress = 40%
2020-01-21 20:09:07.985 [FATAL] CefLoader: Exception of type 'System.OutOfMemoryException' was thrown.
2020-01-21 20:09:08.015 [ERROR] Oops! Something went wrong.     Exception of type 'System.OutOfMemoryException' was thro
wn.        at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ICSharpCode.SharpZipLib.Core.StreamUtils.Copy(Stream source, Stream destination, Byte[] buffer, Action`1 progress)

   at ICSharpCode.SharpZipLib.BZip2.BZip2.Decompress(Stream inStream, Stream outStream, Boolean isStreamOwner, Action`1
progressPercent)
   at Chromely.CefGlue.Loader.CefLoader.DecompressArchive()
   at Chromely.CefGlue.Loader.CefLoader.Load(ChromelyPlatform platform)
   at Chromely.CefGlue.BrowserWindow.CefBinariesLoader.Load(IChromelyConfiguration config)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```                                                                                                                       

The memory usage is about ~30 Mb until the BZ2 decompression phase, then it starts to grow very quickly and the app crashes with 40% success and ~600-700 Mb memory usage.

Any workarounds for this problem? Does it really need 1.5+ Gb memory to unpack properly?

**Comment by mattkol** [comment]
@IlyaSemenov I did see this error too once in a while on Linux distros. This is not something I have personally looked into yet.

Also we are using a thin version of [SharpZipLib](https://github.com/icsharpcode/SharpZipLib) so it may have been addressed in the project or somewhere else.

But note that we just provided the in-built cef binaries loading option just for developers convenience and you really do not have to use it.

You can bypass that by:
````csharp
        var config = DefaultConfiguration.CreateForRuntimePlatform();
       config.CefDownloadOptions.AutoDownloadWhenMissing =  false;
````
https://github.com/chromelyapps/Chromely/blob/1a358986894377da8cffe87e00ce0d5893db690b/src/Chromely.CefGlue/BrowserWindow/CefBinariesLoader.cs#L55

.. and do the [manual download](https://github.com/chromelyapps/Chromely.Legacy/wiki/CefGlue-Application-Layout).

** sorry wiki is still being updated.

If we find something we will keep you posted.

Thanks.

**Comment by mattkol** [comment]
@IlyaSemenov note that the url you need is in the exception:
http://opensource.spotify.com/cefbuilds/cef_binary_77.1.18%
2Bg8e8d602%2Bchromium-77.0.3865.120_windows32_minimal.tar.bz2

.. then after download follow from Step 2 here - https://github.com/chromelyapps/Chromely.Legacy/wiki/CefGlue-Application-Layout

**Comment by IlyaSemenov** [comment]
Thanks for reaching back. Yes, I already discovered all these options and actually replicated the downloader behaviour (copying `Release` and `Resources` contents into the app dir) in my CI/CD pipeline. Unfortunately the app simply crashes now. (Also, it increases the distributable package size greatly so I guess it's not the best option in the long run.)

What is odd is that somehow it used to work on this very computer a couple weeks ago when I was prototyping, and now with the production it build it won't start. Go figure. (I surely understand that you couldn't help with anything like that - just being emotional here :)

**Comment by mattkol** [comment]
@IlyaSemenov I will be honest I have never tried this on Windows 7. But if CEF officially supports Windows 7, then I will say do not give up yet.  Also you need to find out if .NET Core is supported on Windows 7. Those are the primary variables.

Both I never looked closely.

For CEF, try run the cefclient.exe on Windows 7. If that runs successfully, then you are left with .NET Core.

cefclient.exe will be in Client will be in a url like this:
http://opensource.spotify.com/cefbuilds/cef_binary_77.1.18%
2Bg8e8d602%2Bchromium-77.0.3865.120_windows32_client.tar.bz2

**Comment by mattkol** [comment]
Or .. you do only [.NET Framework](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/NetFrameworkDemo).

**Comment by IlyaSemenov** [comment]
I just found my prototyping build from December 2019 and very interestingly it worked, even though it was downloading, unpacking and then running the very same v77 windows32 build.

<img width="622" alt="Screenshot 2020-01-21 at 22 05 06" src="https://user-images.githubusercontent.com/128121/72816390-a17a5300-3c9a-11ea-85d4-cb710c2c107b.png">

Peak memory usage during decompression was ~720Mb then it started normally. I'll try to bisect it from here.

Anyhow, back to the topic, I think `MemoryStream` below should better be replaced with a temporary file stream...it's hundreds of megabytes in either case, not very elegant to keep them in memory without real reason.

https://github.com/chromelyapps/Chromely/blob/a5fcb9059073c90548f16eabe622e3c12b306d85/src/Chromely.CefGlue/Loader/CefLoader.cs#L286-L294

**Comment by FrankPfattheicher** [comment]
@IlyaSemenov as i implemented the downloader i optimized it for speed, so i didn't use a temporary file. But you are right this will be a solution.
Otherwise i did not see a 2GB machine anywhere around - and if so you can download CEF manually and deploy it with yout application.

There is still the issue the decompression takes too long - but that is BZ2 - no real chance to speed it up :-(

**Comment by IlyaSemenov** [comment]
I bisected the problem to this:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
```

makes it crash around 40% and ~530 Mb, while

```xml
<Project Sdk="Microsoft.NET.Sdk">
```

works 'normally' (peaking with 700+ Mb usage but not crashing). This is .net core 3.1.

(Unfortunately I need a single app that runs both the web server **and** the browser...)

**Comment by IlyaSemenov** [comment]
Fixed it by explicitly disabling server garbage collector:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
  </PropertyGroup>
```

and doing a clean build.

**Comment by mattkol** [comment]
@IlyaSemenov I think it is something we can learn from. We should leave this opened for now. 

Thanks for taking time to look at this closely.

**Comment by mattkol** [comment]
Changed MemoryStream to FileStream - https://github.com/chromelyapps/Chromely/commit/bd8b35a751704be0fdb1cbc72fafc43f3cd76523
