### ISSUE TITLE
MIssing libcef on Linux

### ISSUE THREAD

**Issue by mikart143** [chromelyapps/Chromely#192]
Hello!
I am trying to run my app on linux and I am getting strange error:

> 2020-05-01 15:30:12.256 [ERROR] Oops! Something went wrong.     Unable to load shared library 'libcef' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibcef: cannot open shared object file: No such file or directory          at Xilium.CefGlue.Interop.libcef.enable_highdpi_support()
   at Xilium.CefGlue.CefRuntime.EnableHighDpiSupport()
   at Chromely.CefGlue.BrowserWindow.HostBase.RunInternal(String[] args)
   at Chromely.CefGlue.BrowserWindow.HostBase.Run(String[] args)

I added runtime identifire  and also chromium downloaded correctly. libcef.so is present at bin folder.
I am running PopOs 20.04

**Comment by mattkol** [comment]
@mikart143 seem like PopOs is a derivative of Ubuntu. 
Please see list of what we have tested and supported so far -
https://github.com/chromelyapps/Chromely#platforms

Also check to see if related to:
https://github.com/chromelyapps/Chromely/issues/187
https://github.com/chromelyapps/Chromely/pull/188

**Comment by mikart143** [comment]
So I tried to run tests from #188  but It failed on CreateWindow() method:

> 2020-05-01 17:44:25.661 [ERROR] Oops! Something went wrong.     Exception has been thrown by the target of an invocation.          at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Caliburn.Light.SimpleContainer.ActivateInstance(Type type, Object[] args) in /home/mikart/Downloads/Chromely-master/src/Chromely.Core/Infrastructure/SimpleContainer.cs:line 496
   at Caliburn.Light.SimpleContainer.BuildInstance(Type type) in /home/mikart/Downloads/Chromely-master/src/Chromely.Core/Infrastructure/SimpleContainer.cs:line 485
   at Caliburn.Light.SimpleContainer.<>c__DisplayClass9_0.<RegisterSingleton>b__0(SimpleContainer c) in /home/mikart/Downloads/Chromely-master/src/Chromely.Core/Infrastructure/SimpleContainer.cs:line 147
   at Caliburn.Light.SimpleContainer.GetInstance(Type service, String key) in /home/mikart/Downloads/Chromely-master/src/Chromely.Core/Infrastructure/SimpleContainer.cs:line 374
   at Chromely.ChromelyBasicApp.CreateWindow() in /home/mikart/Downloads/Chromely-master/src/Chromely/ChromelyBasicApp.cs:line 38
   at Chromely.Core.AppBuilder.Run(String[] args) in /home/mikart/Downloads/Chromely-master/src/Chromely.Core/AppBuilder.cs:line 124

Everything is updated, dotnet command is present. I did not changed my Gnome to anything else because most of my users will use Gnome. libcef.so is present and it is 904 MB. I tried to run test from #188 but it failed.

**Comment by mattkol** [comment]
@mikart143  please ensure you are not mixing the assemblies - there was a change to the SimpleContainer about 2 weeks or so .. the issue you see may be related to that.

https://github.com/chromelyapps/Chromely/commit/1589d83206f05e2ede4e5b9f173a5e4d6d5f8cc8#diff-3b58baf3508d7be93b31b46b8993d4cd

**Comment by mikart143** [comment]
Sorry but I do not understand. Where I probably mixed assemblies ? In test or in my app ?

**Comment by mattkol** [comment]
There are 3 assemblies

Chromely.Core
Chromely.CefGlue
Chromely

If you are using source code, better to use source code for all. That is what I mean.

So what you find may be correct, but good to be sure. The changes have only been tested by a few people and not on Linux/MacOS yet.

**Comment by behaug** [comment]
I am seeing something similar on MacOSX. 

When invoking "dotnet run" it downloads cef, extracts it and then gives an error:

```
2020-05-02 01:12:16.258 [INFO] Running MacOSX chromium 77.0.3865.120
2020-05-02 01:12:16.275 [ERROR] Oops! Something went wrong.	Unable to load shared library 'libcef' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibcef, 1): image not found	   at Xilium.CefGlue.Interop.libcef.api_hash(Int32 entry)
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
   at Xilium.CefGlue.CefRuntime.CheckVersion()
   at Xilium.CefGlue.CefRuntime.Load(String path)
   at Xilium.CefGlue.CefRuntime.Load()
   at Chromely.CefGlue.BrowserWindow.CefBinariesLoader.Load(IChromelyConfiguration config)
2020-05-02 01:12:16.291 [INFO] CefLoader: Installing CEF runtime from http://opensource.spotify.com/cefbuilds
2020-05-02 01:12:16.325 [INFO] CefLoader: Load CEF for MacOSX X64, version 3865
2020-05-02 01:12:16.327 [INFO] CefLoader: Load index page http://opensource.spotify.com/cefbuilds/index.html#macosx64_builds
2020-05-02 01:12:16.922 [INFO] CefLoader: Found download URL http://opensource.spotify.com/cefbuilds/cef_binary_77.1.18%2Bg8e8d602%2Bchromium-77.0.3865.120_macosx64_minimal.tar.bz2
2020-05-02 01:12:16.952 [INFO] CefLoader: Parallel download cef_binary_77.1.18%2Bg8e8d602%2Bchromium-77.0.3865.120_macosx64_minimal.tar.bz2, 63MB
2020-05-02 01:12:16.979 [INFO] CefLoader: Load /var/folders/dx/s24_dlw516qctm2xg55_mdjr0000gn/T/tmpk1nCCA.tmp (0..8321494)
[......]
2020-05-02 01:12:39.030 [INFO] CefLoader: Extracting cef_binary_77.1.18+g8e8d602+chromium-77.0.3865.120_macosx64_minimal/Debug/cef_sandbox.a
2020-05-02 01:12:39.041 [INFO] CefLoader: Decompressing archive took 17161ms
2020-05-02 01:12:39.042 [INFO] CefLoader: Copy files to application directory
2020-05-02 01:12:39.401 [INFO] CefLoader: Copying files took 359ms
[0502/011241.650292:ERROR:icu_util.cc(129)] icudtl.dat not found in bundle
[0502/011241.650444:ERROR:icu_util.cc(165)] Invalid file descriptor to ICU data received.
```

If I run "dotnet run" again it doesn't download anymore but just repeats those last 2 lines from icu_util.

The icudtl.dat is present in my bin/Debug/netcoreapp3.1 directory.

**Comment by mattkol** [comment]
@behaug I have seen developers raise this issue a few times. I personally do not know why it happens. I always suggest a refresh/redo or to be pretty sure, CEF download was not corrupted that developers try a manual download.

Please let me know if this helps - https://github.com/chromelyapps/Chromely/issues/175#issuecomment-610350084

We may need to zoom in somehow to see why this happens.

Thanks.

**Comment by behaug** [comment]
I deleted my bin directory and run "dotnet build" over again, so I have my application with no cef. I then downloaded it manually as described here: https://github.com/chromelyapps/Chromely/blob/9e7b079053279df51487a5940a6c8db054574cd3/Documents/cef_binaries_download.md

But it still gives me the exact same error message.

```
2020-05-02 02:21:41.053 [INFO] Running MacOSX chromium 77.0.3865.120
[0502/022141.208076:ERROR:icu_util.cc(129)] icudtl.dat not found in bundle
[0502/022141.209087:ERROR:icu_util.cc(165)] Invalid file descriptor to ICU data received.
```

Should I try a newer version of chromium or is Chromely built to this version?

**Comment by behaug** [comment]
I see in this commit https://github.com/chromelyapps/Chromely/commit/b657d24505590a1c8bffab98c124aa335b4e675f that you upgraded to Chromium 79. But that is not yet available in the nuget version of Chromely (5.0.77.3) because when I manually download version 79 I get this error:

```
2020-05-02 02:47:44.494 [INFO] Running MacOSX chromium 77.0.3865.120
2020-05-02 02:47:44.589 [ERROR] Oops! Something went wrong.	CEF runtime version mismatch: loaded version API hash "4a77f1908fabccdb01a2d3bdbede5ca09fbaa394", but supported "1c87ca78fce1bd15cd78f33f8f4e1763d616556a" (77.1.18+g8e8d602+chromium-77.0.3865.120).	   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
   at Xilium.CefGlue.CefRuntime.CheckVersion()
   at Xilium.CefGlue.CefRuntime.Load(String path)
   at Xilium.CefGlue.CefRuntime.Load()
   at Chromely.CefGlue.BrowserWindow.CefBinariesLoader.Load(IChromelyConfiguration config)

```

**Comment by mattkol** [comment]
@behaug CefGlue does not give us the liberty of changing versions at will - https://github.com/chromelyapps/Chromely/blob/master/src/Chromely.CefGlue/CefGlue/Interop/version.g.cs. Of course we could separate CefGlue into a separate DLL but we wanted to make things simpler so we embedded the code. CefGlue itself does not have nugets published, we had to manage that too, if we go that route. 

But the issue  you are having seems more like dependencies missing or security issue. Is it possible you debug using Visual Studio Code? Maybe some .Net Core libs missing or versioning issue. It was tough to get MacOS right, but it has been smooth sailing for a while now. And on MacOS the CEF binaries load pretty fast - my experience.

Also if you can share your Mac version, we can check if there are CEF issues around that.

So using Visual Studio Code, I will start from the basics:
dotnet restore
dotnet build
dotnet run

If anything missing, restore, or build should point it out.

Thanks

**Comment by mikart143** [comment]
I tried download manually chromium and add to project but the same issue is still present. Could this be a chromium issue ?

**Comment by mattkol** [comment]
@mikart143 will be hard to tell. First time I am hearing about PopOs 20.04 is from you. So it may not be widely used in the CEF community. Or it is just me.

But still, it is based on Ubuntu, so should work if basic things are not changed in the distro.

Unfortunately with the bandwidth we have on Chromely project we cannot support every Linux distros out there. There are many many.

I will suggest you use Visual Studio Code to debug and that may help. I usually just flatten the source code to help me debug on Linux and MacOS using VSC.

Attached is an example of what I meant. You can try this for v77 and do same for v79 (current repo) if need be,

Thanks.
[Chromelyv77.zip](https://github.com/chromelyapps/Chromely/files/4567610/Chromelyv77.zip)

**Comment by mattkol** [comment]
@mikart143  remember to  change the runtime to Linux in the project file.
