### ISSUE TITLE
 Oops! Something went wrong.     Unable to load shared library 'kernel32.dll' 

### ISSUE THREAD

**Issue by dreamsfly900** [chromelyapps/Chromely#240]
centos 7 error:

Oops! Something went wrong.     Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll

**Comment by dreamsfly900** [comment]
es=OutOfBlinkCors --no-sandbox --locales-dir-path=/home/ceshi/winform/locales --log-file=logs\chromely.cef_20200825.log --log-severity=info --resources-dir-path=/home/ceshi/winform --lang=en-US --default-encoding=utf-8 --allow-file-access-from-files --allow-universal-access-from-files --disable-web-security --ignore-certificate-errors
[0825/000358.039570:ERROR:edid_parser.cc(102)] Too short EDID data: manufacturer id

DevTools listening on ws://127.0.0.1:20480/devtools/browser/1db7f4fb-2e5a-4356-9b98-dfaa2a1e70f4
2020-08-25 00:03:58.083 [ERROR] Oops! Something went wrong.     Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: 无法打开共享对象文件: 没有那个文件或目录         at Chromely.Native.WinNativeMethods.GetConsoleWindow()
   at Chromely.Native.WinAPIHost.CreateWindow(IWindowOptions options, Boolean debugging)
   at Chromely.Windows.NativeWindow.ShowWindow()
   at Chromely.Windows.Window..ctor(IChromelyNativeHost nativeHost, IChromelyContainer container, IChromelyConfiguration config, IChromelyCommandTaskRunner commandTaskRunner, CefMessageRouterBrowserSide browserMessageRouter)
   at Chromely.Windows.ChromelyWindow.CreateMainView()
   at Chromely.CefGlue.BrowserWindow.HostBase.CreateMainWindow()
   at Chromely.CefGlue.BrowserWindow.HostBase.RunInternal(String[] args)
   at Chromely.CefGlue.BrowserWindow.HostBase.Run(String[] args)
[root@localhost winform]# 2020-08-25 00:03:58.209 [INFO] Running Linux chromium 83.0.4103.106
[0825/000358.278827:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[root@localhost winform]# [0825/000413.286641:INFO:child_thread_impl.cc(839)] ChildThreadImpl::EnsureConnected()
[root@localhost winform]# ^C

**Comment by mattkol** [comment]
@dreamsfly900 

What OS platform is this? I believe centos 7 is a linux distro, but it seems you are running  Chromely on Windows.

Please [readme](https://github.com/chromelyapps/demo-projects).
Also see - https://github.com/chromelyapps/Chromely/issues/228

**Comment by dreamsfly900** [comment]
centos 7

**Comment by mattkol** [comment]
So Linux.
Then you are likely not doing something right.
Please read the guide and start again.

If that does not help, you can share skeletal code of what you are doing.
