### ISSUE TITLE
Troubles w/ cef downgrade

### ISSUE THREAD

**Issue by h3xb0y** [chromelyapps/Chromely#288]
After downgrading cef for [CrossPlatDemo](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo) by [guide](https://github.com/chromelyapps/Chromely/blob/master/Documents/cef_binaries_download.md) application gots error on boot 

```
2021-01-16T23:03:13.7764486+02:00  [ERR] CEF runtime version mismatch: loaded version API hash "e5386095f03ffc204bdeacac7a13275918c66eb1", but supported "3022db6736af26cc38158d38e22f74a51312a5c9" (86.0.21+g6a2c8e7+chromium-86.0.4240.183). (4af254b1)
Xilium.CefGlue.CefVersionMismatchException: CEF runtime version mismatch: loaded version API hash "e5386095f03ffc204bdeacac7a13275918c66eb1", but supported "3022db6736af26cc38158d38e22f74a51312a5c9" (86.0.21+g6a2c8e7+chromium-86.0.4240.183).
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
   at Xilium.CefGlue.CefRuntime.CheckVersion()
   at Xilium.CefGlue.CefRuntime.Load(String path)
   at Xilium.CefGlue.CefRuntime.Load()
   at Chromely.Loader.CefBinariesLoader.Load(IChromelyConfiguration config)
```

what im doing wrong?

**Comment by mattkol** [comment]
You cannot downgrade CEF binaries version for a specific CefGlue version.

**Comment by h3xb0y** [comment]
i downgraded CefGlue version and it works, thx
