### ISSUE TITLE
COM Interop is not supported on this platform.

### ISSUE THREAD

**Issue by brandochn** [chromelyapps/Chromely#383]
Hi Guys,

I have downloaded the latest source code of demo-projects and I adjusted the Chromely.CrossPlat project to work on Linux platform and I got the following error:

```
$ dotnet run --project Chromely.CrossPlat
Unhandled exception. System.PlatformNotSupportedException: COM Interop is not supported on this platform.
   at System.Threading.Thread.SetApartmentStateUnchecked(ApartmentState state, Boolean throwOnError)
   at System.Threading.Thread.SetApartmentState(ApartmentState state, Boolean throwOnError)
   at System.Threading.Thread.SetApartmentState(ApartmentState state)
   at Chromely.NativeHosts.ThreadApt.STA()
   at Program.<Main>$(String[] args) in /Chromely/demo-projects/regular-chromely/Chromely.CrossPlat/Program.cs:line 10
```

![imagen](https://user-images.githubusercontent.com/32686301/187080393-991c8c13-8f6a-4009-9a83-51919d55d790.png)

![imagen](https://user-images.githubusercontent.com/32686301/187080437-8bb81d4b-3445-4a29-b4ba-3365e373a28b.png)

I ran this into 
OS: Fedora 36 x64.
.Net: 6.0.107

**Comment by brandochn** [comment]
@seerkong I commented the line: `ThreadApt.STA();` and the Chromely.CrossPlat project is working well.

Thank you.
