### ISSUE TITLE
Auto download of libcef - 403

### ISSUE THREAD

**Issue by grbd** [chromelyapps/Chromely#99]
Hi,
I think this is more of a minor issue but just something I spotted for info
When we use Chromely via Nuget it will automatically install the files needed for libcef at the same time.
Typically this includes
```
*.pak
*.bin
*.dat
locales/
chrome_elf.dll
libcef.dll
libEGL.dll
libGLESv2.dll
```

I think when you try building against a development version of Chromely which is not via Nuget (just referencing the dll file such as Chromely.CefGlue.dll) it tries to be clever and auto download the libcef files from I'm guessing here http://opensource.spotify.com/cefbuilds/index.html based on a specific version

It looks like the auto download may be broken (reports a 403 error)
Again this doesn't affect Nuget packages just the use of development dll's so is a fairly minor thing.

**Comment by grbd** [comment]
also awesome work on the subprocess stuff, this launches a lot quicker than Electron.Net
I'm going to see if I can get a couple of additional demo's setup including something that will run on a Rpi

**Comment by mattkol** [comment]
@grbd on the auto download issue, does it have a detailed error in the logs or console output?

**Comment by grbd** [comment]
In the logs it shows
```
2019-05-20 14:24:36.924 [INFO] Running Windows chromium 70.0.3538.102
2019-05-20 14:24:36.951 [ERROR] Oops! Something went wrong.	Unable to load DLL 'libcef': The specified module could not be found. (Exception from HRESULT: 0x8007007E)	   at Xilium.CefGlue.Interop.libcef.api_hash(Int32 entry)
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
   at Xilium.CefGlue.CefRuntime.CheckVersion()
   at Xilium.CefGlue.CefRuntime.Load(String path)
   at Xilium.CefGlue.CefRuntime.Load()
   at Chromely.CefGlue.BrowserWindow.CefBinariesLoader.Load(ChromelyConfiguration config)
2019-05-20 14:24:37.114 [INFO] CefLoader: Installing CEF runtime from http://opensource.spotify.com/cefbuilds
2019-05-20 14:24:37.156 [INFO] CefLoader: Load CEF for Windows X64, version 0
2019-05-20 14:24:37.669 [FATAL] CefLoader: CEF for chrome version 70.0.3538.102 platform windows64 not found.
2019-05-20 14:24:37.772 [FATAL] CefLoader: The remote server returned an error: (403) Forbidden.
2019-05-20 14:24:37.786 [ERROR] Oops! Something went wrong.	The remote server returned an error: (403) Forbidden.	   at System.Net.HttpWebRequest.GetResponse()
   at Chromely.CefGlue.Loader.CefLoader.Download()
   at Chromely.CefGlue.Loader.CefLoader.Load()
   at Chromely.CefGlue.BrowserWindow.CefBinariesLoader.WarnUserOnLoad()

```

Maybe they changed they're url http://opensource.spotify.com seems to redirect to https://www.spotify.com/uk/opensource/

And the download link for that version on the website appears to be https://gsdview.appspot.com/chromium-browser-official/chromium-70.0.3538.102.tar.xz

**Comment by grbd** [comment]
Hmm I recently tried a publish of the demo app Chromely.CefGlue.Gtk.Linux.Demo to the ubuntu.16.10-x64 target. Then ran that on a gentoo x64 vm, It triggered the download of libcef and worked fine.
Might just be related to windows

**Comment by mattkol** [comment]
@grbd thanks for the updates.
